name: quit_gambling
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  kartal: ^4.1.0
  vibration: ^3.1.2
  gradient_circular_progress_indicator: ^0.0.4
  lottie: ^3.2.0
  shared_preferences: ^2.5.2
  simple_gradient_text: ^1.3.0
  superwallkit_flutter: ^1.3.10
  in_app_review: ^2.0.10
  intl: ^0.20.2
  mixpanel_flutter: ^2.3.3
  pull_down_button: ^0.10.2
  url_launcher: ^6.3.1
  home_widget: ^0.7.0+1
  uni_links2: ^0.6.0+2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
